### PR TITLE
changed CHD coordinates to float

### PR DESCRIPTION
**Pull request by amous4822**
I was trying to run the 'Exploring venues in Chandigarh.ipynb' file but then there were errors due to the type of location coordinates used.

### CODE REVIEW

**Comment by kb22** [comment]
I've tried the code and it works with string values as well. What error were you facing?

**Comment by amous4822** [comment]
RuntimeError: maximum recursion depth exceeded in cmp.

Here's a link to the screenshot:

https://user-images.githubusercontent.com/31563113/67091985-ba6ef600-f1cb-11e9-8360-e447625a1fe0.png

**Comment by kb22** [comment]
I don’t find any runtime errors in the code as I ran it yesterday.
Can you tell me the following:
1 Any changes made to the code?
2 Is the error screenshot complete?

Also, for best results, use Python 3.6
It appears that you’re using Python 2.7

**Comment by amous4822** [comment]
It's working now. The 2.7 version got installed in my virtual environment 😅. I'm sorry for the PR.

**Pull request closed without merging**
